# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mineru.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mineru.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmineru.proto\x12\x14historyrag.mineru.v1\"\xd9\x01\n\x0fParsePdfRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\x12\x15\n\rlanguage_hint\x18\x03 \x01(\t\x12\x13\n\x0blayout_hint\x18\x04 \x01(\t\x12\x1a\n\x12\x64ocument_type_hint\x18\x05 \x01(\t\x12 \n\x18\x62ook_page_start_pdf_page\x18\x06 \x01(\t\x12\x1d\n\x15\x62ook_page_start_value\x18\x07 \x01(\t\x12\x15\n\rmodel_version\x18\x08 \x01(\t\"_\n\x10ParsePdfResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12:\n\x08\x64ocument\x18\x02 \x01(\x0b\x32(.historyrag.mineru.v1.StructuredDocument\"a\n\x12StructuredDocument\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tfull_text\x18\x02 \x01(\t\x12)\n\x05pages\x18\x03 \x03(\x0b\x32\x1a.historyrag.mineru.v1.Page\"\xca\x01\n\x04Page\x12\x13\n\x0bpdf_page_no\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x33\n\nparagraphs\x18\x03 \x03(\x0b\x32\x1f.historyrag.mineru.v1.Paragraph\x12\x0f\n\x07page_no\x18\x04 \x01(\x05\x12\x14\n\x0c\x62ook_page_no\x18\x05 \x01(\x05\x12\x1a\n\x12page_number_source\x18\x06 \x01(\t\x12\x12\n\npage_width\x18\x07 \x01(\x05\x12\x13\n\x0bpage_height\x18\x08 \x01(\x05\"\xc7\x01\n\tParagraph\x12\x14\n\x0cparagraph_id\x18\x01 \x01(\t\x12\x14\n\x0cparagraph_no\x18\x02 \x01(\x05\x12\x1b\n\x13paragraph_no_in_doc\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x12\n\nline_start\x18\x05 \x01(\x05\x12\x10\n\x08line_end\x18\x06 \x01(\x05\x12(\n\x04\x62\x62ox\x18\x07 \x01(\x0b\x32\x1a.historyrag.mineru.v1.BBox\x12\x13\n\x0b\x62\x62ox_source\x18\x08 \x01(\t\";\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05width\x18\x03 \x01(\x01\x12\x0e\n\x06height\x18\x04 \x01(\x01\x32o\n\x12MineruPdfExtractor\x12Y\n\x08ParsePdf\x12%.historyrag.mineru.v1.ParsePdfRequest\x1a&.historyrag.mineru.v1.ParsePdfResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mineru_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEPDFREQUEST']._serialized_start=39
  _globals['_PARSEPDFREQUEST']._serialized_end=256
  _globals['_PARSEPDFRESPONSE']._serialized_start=258
  _globals['_PARSEPDFRESPONSE']._serialized_end=353
  _globals['_STRUCTUREDDOCUMENT']._serialized_start=355
  _globals['_STRUCTUREDDOCUMENT']._serialized_end=452
  _globals['_PAGE']._serialized_start=455
  _globals['_PAGE']._serialized_end=657
  _globals['_PARAGRAPH']._serialized_start=660
  _globals['_PARAGRAPH']._serialized_end=859
  _globals['_BBOX']._serialized_start=861
  _globals['_BBOX']._serialized_end=920
  _globals['_MINERUPDFEXTRACTOR']._serialized_start=922
  _globals['_MINERUPDFEXTRACTOR']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
